// Canonical 2026 World Cup stadium and city data. The fixture provider does not
// expose venues, so these are keyed by its stable fixture IDs. Names are intentionally
// not localized.
const VENUES_BY_FIXTURE_ID = {
  537327: { name: "Estadio Azteca", city: "Mexico City" },
  537328: { name: "Estadio Akron", city: "Guadalajara" },
  537329: { name: "Mercedes-Benz Stadium", city: "Atlanta" },
  537330: { name: "Estadio Akron", city: "Guadalajara" },
  537331: { name: "Estadio Azteca", city: "Mexico City" },
  537332: { name: "Estadio BBVA", city: "Monterrey" },
  537333: { name: "BMO Field", city: "Toronto" },
  537334: { name: "Levi's Stadium", city: "San Francisco Bay Area" },
  537335: { name: "SoFi Stadium", city: "Los Angeles" },
  537336: { name: "BC Place", city: "Vancouver" },
  537337: { name: "BC Place", city: "Vancouver" },
  537338: { name: "Lumen Field", city: "Seattle" },
  537339: { name: "MetLife Stadium", city: "New York/New Jersey" },
  537340: { name: "Gillette Stadium", city: "Boston" },
  537341: { name: "Lincoln Financial Field", city: "Philadelphia" },
  537342: { name: "Gillette Stadium", city: "Boston" },
  537343: { name: "Hard Rock Stadium", city: "Miami" },
  537344: { name: "Mercedes-Benz Stadium", city: "Atlanta" },
  537345: { name: "SoFi Stadium", city: "Los Angeles" },
  537346: { name: "BC Place", city: "Vancouver" },
  537347: { name: "Levi's Stadium", city: "San Francisco Bay Area" },
  537348: { name: "Lumen Field", city: "Seattle" },
  537349: { name: "SoFi Stadium", city: "Los Angeles" },
  537350: { name: "Levi's Stadium", city: "San Francisco Bay Area" },
  537351: { name: "NRG Stadium", city: "Houston" },
  537352: { name: "Lincoln Financial Field", city: "Philadelphia" },
  537353: { name: "BMO Field", city: "Toronto" },
  537354: { name: "GEHA Field at Arrowhead Stadium", city: "Kansas City" },
  537355: { name: "MetLife Stadium", city: "New York/New Jersey" },
  537356: { name: "Lincoln Financial Field", city: "Philadelphia" },
  537357: { name: "AT&T Stadium", city: "Dallas" },
  537358: { name: "Estadio BBVA", city: "Monterrey" },
  537359: { name: "NRG Stadium", city: "Houston" },
  537360: { name: "Estadio BBVA", city: "Monterrey" },
  537361: { name: "GEHA Field at Arrowhead Stadium", city: "Kansas City" },
  537362: { name: "AT&T Stadium", city: "Dallas" },
  537363: { name: "Lumen Field", city: "Seattle" },
  537364: { name: "SoFi Stadium", city: "Los Angeles" },
  537365: { name: "SoFi Stadium", city: "Los Angeles" },
  537366: { name: "BC Place", city: "Vancouver" },
  537367: { name: "BC Place", city: "Vancouver" },
  537368: { name: "Lumen Field", city: "Seattle" },
  537369: { name: "Mercedes-Benz Stadium", city: "Atlanta" },
  537370: { name: "Hard Rock Stadium", city: "Miami" },
  537371: { name: "Mercedes-Benz Stadium", city: "Atlanta" },
  537372: { name: "Hard Rock Stadium", city: "Miami" },
  537373: { name: "Estadio Akron", city: "Guadalajara" },
  537374: { name: "NRG Stadium", city: "Houston" },
  537375: { name: "Lincoln Financial Field", city: "Philadelphia" },
  537376: { name: "NRG Stadium", city: "Houston" },
  537377: { name: "MetLife Stadium", city: "New York/New Jersey" },
  537378: { name: "Estadio Azteca", city: "Mexico City" },
  537379: { name: "AT&T Stadium", city: "Dallas" },
  537380: { name: "Lumen Field", city: "Seattle" },
  537381: { name: "Mercedes-Benz Stadium", city: "Atlanta" },
  537382: { name: "BC Place", city: "Vancouver" },
  537383: { name: "Gillette Stadium", city: "Boston" },
  537384: { name: "SoFi Stadium", city: "Los Angeles" },
  537385: { name: "Hard Rock Stadium", city: "Miami" },
  537386: { name: "GEHA Field at Arrowhead Stadium", city: "Kansas City" },
  537387: { name: "AT&T Stadium", city: "Dallas" },
  537388: { name: "Mercedes-Benz Stadium", city: "Atlanta" },
  537389: { name: "Hard Rock Stadium", city: "Miami" },
  537390: { name: "MetLife Stadium", city: "New York/New Jersey" },
  537391: { name: "MetLife Stadium", city: "New York/New Jersey" },
  537392: { name: "Gillette Stadium", city: "Boston" },
  537393: { name: "Lincoln Financial Field", city: "Philadelphia" },
  537394: { name: "MetLife Stadium", city: "New York/New Jersey" },
  537395: { name: "Gillette Stadium", city: "Boston" },
  537396: { name: "BMO Field", city: "Toronto" },
  537397: { name: "GEHA Field at Arrowhead Stadium", city: "Kansas City" },
  537398: { name: "Levi's Stadium", city: "San Francisco Bay Area" },
  537399: { name: "AT&T Stadium", city: "Dallas" },
  537400: { name: "Levi's Stadium", city: "San Francisco Bay Area" },
  537401: { name: "AT&T Stadium", city: "Dallas" },
  537402: { name: "GEHA Field at Arrowhead Stadium", city: "Kansas City" },
  537403: { name: "NRG Stadium", city: "Houston" },
  537404: { name: "Estadio Azteca", city: "Mexico City" },
  537405: { name: "NRG Stadium", city: "Houston" },
  537406: { name: "Estadio Akron", city: "Guadalajara" },
  537407: { name: "Hard Rock Stadium", city: "Miami" },
  537408: { name: "Mercedes-Benz Stadium", city: "Atlanta" },
  537409: { name: "AT&T Stadium", city: "Dallas" },
  537410: { name: "BMO Field", city: "Toronto" },
  537411: { name: "Gillette Stadium", city: "Boston" },
  537412: { name: "BMO Field", city: "Toronto" },
  537413: { name: "MetLife Stadium", city: "New York/New Jersey" },
  537414: { name: "Lincoln Financial Field", city: "Philadelphia" },
  537415: { name: "Gillette Stadium", city: "Boston" },
  537416: { name: "MetLife Stadium", city: "New York/New Jersey" },
  537417: { name: "SoFi Stadium", city: "Los Angeles" },
  537418: { name: "Estadio BBVA", city: "Monterrey" },
  537419: { name: "BMO Field", city: "Toronto" },
  537420: { name: "SoFi Stadium", city: "Los Angeles" },
  537421: { name: "Levi's Stadium", city: "San Francisco Bay Area" },
  537422: { name: "Lumen Field", city: "Seattle" },
  537423: { name: "NRG Stadium", city: "Houston" },
  537424: { name: "AT&T Stadium", city: "Dallas" },
  537425: { name: "Estadio Azteca", city: "Mexico City" },
  537426: { name: "Mercedes-Benz Stadium", city: "Atlanta" },
  537427: { name: "Hard Rock Stadium", city: "Miami" },
  537428: { name: "AT&T Stadium", city: "Dallas" },
  537429: { name: "BC Place", city: "Vancouver" },
  537430: { name: "GEHA Field at Arrowhead Stadium", city: "Kansas City" },
};

export function venueForFixture(id) {
  return VENUES_BY_FIXTURE_ID[id] || null;
}

export const venueFixtureCount = Object.keys(VENUES_BY_FIXTURE_ID).length;
